### ISSUE TITLE
Is there any option for multi-regional sampling?

### ISSUE THREAD

**Issue by biosurgeon** [raphael-group/machina#14]
Hi, 

I have samples matched primary and metastatic tumors, and primary samples are multi-regional one. (bulk-WESs)
it seemed MACHINA can set one primary sample. 
Is there any option for multi-regional samples?

**Comment by gsatas** [comment]
Hi,

In tree inference (PHM-TI) mode, the input file has separate columns for
sample index/label and anatomical site index/label. If you have multiple
samples from the primary tumor, then these samples would all have different
sample labels, but the same anatomical site label. Then, you can set the
anatomical site to be the primary.

Hope this helps!

**Comment by biosurgeon** [comment]
Oh. Thanks so much for quick response and the information. 
I'll try !!
