### ISSUE TITLE
Copy-neutral assumption of MACHINA

### ISSUE THREAD

**Issue by ShaiberAlon** [raphael-group/machina#17]
Hi,

Thank you for creating this tool and making it accessible and easy to use!

I have a question regarding the copy-neutral assumption made by MACHINA: I understand that MACHINA only considers copy-neutral SNVs and I wonder:
1. What is your recommendation re: tumors that have undergone whole genome duplication
2. Did you go through any steps to verify that copy-neutral SNVs are not in regions that have undergone duplication before/after a loss of heterozygosity (LOH) event? (so hence the copy number would appear neutral, but VAF counts might be misleading)

**Comment by braphael8** [comment]
Hi,
Great questions!  First, note that MACHINA has three modes and the first two (pmh and pmh_tr) can run with a clone tree as input, and in this mode does not make any assumptions about copy neutral events.

In the third mode (pmh_ti), mutation frequencies are required as input.  Ideally, these are cancer cell fractions (CCFs) which correctly account for copy number aberrations and WGD.  However, calculating CCFs from VAFs is not always straightforward -- your example describes one of the more difficult cases.  To address these cases, we recently developed DeCiFER, which computes descendant cell fractions (DCFs) for single-nucleotide mutations in the presence of copy number aberrations.  
See preprint here:  https://www.biorxiv.org/content/10.1101/2021.02.27.429196v1
Software here: https://github.com/raphael-group/decifer

We have used the output of DeCiFer as input to MACHINA.  However,  this is not straightforward  using the current releases of the DeCiFer.  We are actively improving this link now.  Please let us know if you are interested in testing this.

**Comment by ShaiberAlon** [comment]
Hi Ben,
Thank you very much for the detailed response! The combination of DeCiFer and MACHINA looks very promising. I will discuss with team members and if/when I or anyone else on the team will be ready to give it a try then we will definitely reach out. Thank you!

**Comment by mkinnaman** [comment]
> Hi,
> Great questions! First, note that MACHINA has three modes and the first two (pmh and pmh_tr) can run with a clone tree as input, and in this mode does not make any assumptions about copy neutral events.
> 
> In the third mode (pmh_ti), mutation frequencies are required as input. Ideally, these are cancer cell fractions (CCFs) which correctly account for copy number aberrations and WGD. However, calculating CCFs from VAFs is not always straightforward -- your example describes one of the more difficult cases. To address these cases, we recently developed DeCiFER, which computes descendant cell fractions (DCFs) for single-nucleotide mutations in the presence of copy number aberrations.
> See preprint here: https://www.biorxiv.org/content/10.1101/2021.02.27.429196v1
> Software here: https://github.com/raphael-group/decifer
> 
> We have used the output of DeCiFer as input to MACHINA. However, this is not straightforward using the current releases of the DeCiFer. We are actively improving this link now. Please let us know if you are interested in testing this.

Hi Ben - 

I would be interested in testing this if you could share the code.

Thanks,
Michael
