### ISSUE TITLE
generate dot file along with pmh function

### ISSUE THREAD

**Issue by qiao-jp** [raphael-group/machina#19]
Hi there,

I tried the main functions before, and the output included both result.txt file and the dot files ready to transfer to plots. I'm trying the pmh_ti function on another dataset recently but there's no dot file generated, it only produced the result txt file. Is there a parameter that i can setup to automatically produce dot file/plots along with the main functions, rather than create all the vertex and leaf labeling and use the visualizemigrationgraph function? Please let me know. Thanks in advance.

Best,
J.

**Comment by melkebir** [comment]
Can you share the arguments that you used? `pmh-ti` does produce dot files. Here's an example execution:

```
[melkebir@ada build]$ ./pmh_ti -p breast -c ../data/hoadley_2016/coloring.txt -m 1 -o A7 -F ../data/hoadley_2016/A7/A7_MACHINA_0.95.tsv -barT A7/mutation_trees.txt
Read 2 mutation trees.

Set parameter Username
Academic license - for non-commercial use only - expires 2023-10-22
Set parameter LazyConstraints to value 1
0-	(PS, S)	5	5	2	mS	5146.83	5146.83	9.31397
Set parameter Username
Academic license - for non-commercial use only - expires 2023-10-22
Set parameter LazyConstraints to value 1
1-	(PS, S)	5	5	2	mS	5146.83	5146.83	8.94178

[melkebir@ada build]$ cd A7
[melkebir@ada A7]$ ls
0-G-breast-S.dot   0-log-breast-S.txt     0-T-breast-S.tree  1-GG-breast-S.dot   1-T-breast-S.labeling
0-G-breast-S.tree  0-T-breast-S.dot       1-G-breast-S.dot   1-log-breast-S.txt  1-T-breast-S.tree
0-GG-breast-S.dot  0-T-breast-S.labeling  1-G-breast-S.tree  1-T-breast-S.dot    mutation_trees.txt
```
