### ISSUE TITLE
Problem installing machina

### ISSUE THREAD

**Issue by jmfa** [raphael-group/machina#2]
Hi,

I'm trying to install machina but I'm running into some problems with the lemon package. I tried your recommendations in the cmake step (which finishes without any error) but still get the following error message when i run make:
`~/MACHINA/machina/src/utils.h:12:28: fatal error: lemon/adaptors.h: No such file or directory`

Here's my cmake command:
`cmake -DLIBLEMON_ROOT=~/MACHINA/machina/lemon/lemon-1.0/  \
 -DGUROBI_INCLUDE_DIR=/Library/gurobi752/mac64/include \
 -DGUROBI_CPP_LIB=/Library/gurobi752/mac64/lib/libgurobi_c++.a \
 -DGUROBI_LIB=/usr/local/lib/libgurobi75.so ..`

Am I doing something wrong?
Thanks in advance,
Joao

**Comment by jmfa** [comment]
Sorry, just realized that I was using an older version of Lemon. However, I'm still struggling to install machina. Here's the errors I get:
`[ 15%] Linking CXX executable pmh_tr
Undefined symbols for architecture x86_64:
  "GRBEnv::GRBEnv(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
      IlpSolver::IlpSolver(CloneTree const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MigrationGraph::Pattern, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::list<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&) in ilpsolver.cpp.o
      IlpSolver::IlpSolver(CloneTree const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MigrationGraph::Pattern, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::list<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&) in ilpsolver.cpp.o
      IlpPmhSolver::IlpPmhSolver(CloneTree const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MigrationGraph::Pattern, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::list<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&) in ilppmhsolver.cpp.o
      IlpPmhSolver::IlpPmhSolver(CloneTree const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MigrationGraph::Pattern, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::list<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&) in ilppmhsolver.cpp.o
  "GRBModel::write(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
      IlpSolver::exportModel(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in ilpsolver.cpp.o
      IlpSolver::run(CloneTree const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > > const&, MigrationGraph::Pattern, int, bool, bool, int, std::pair<int, std::pair<int, int> > const&, std::list<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&) in ilpsolver.cpp.o
      IlpPmhSolver::exportModel(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in ilppmhsolver.cpp.o
      IlpPmhSolver::run(IlpPmhSolver&, CloneTree const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > > const&, MigrationGraph::Pattern, int, bool, bool, int, std::pair<int, std::pair<int, int> > const&, std::list<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&) in ilppmhsolver.cpp.o
  "GRBModel::addVar(double, double, double, char, std::basic_string<char, std::char_traits<char>, std::allocator<char> >)", referenced from:
      IlpSolver::initVariables()      in ilpsolver.cpp.o
      IlpBinarizationSolver::initVariables()       in ilpbinarizationsolver.cpp.o
      IlpPmhTrSolver::initVariables()       in ilppmhtrsolver.cpp.o
      IlpPmhTrSolver::initLeafVariables()       in ilppmhtrsolver.cpp.o
      IlpPmhSolver::initLeafVariables()       in ilppmhsolver.cpp.o
      IlpPmhSolver::initVariables()       in ilppmhsolver.cpp.o
  "GRBModel::addConstr(GRBTempConstr const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >)", referenced from:
      IlpSolver::initParallelSingleSourceSeedingConstraints()      in ilpsolver.cpp.o
      IlpSolver::initPrimaryConstraint(lemon::ListDigraphBase::Node)       in ilpsolver.cpp.o
      IlpSolver::initSingleSourceSeedingConstraints()      in ilpsolver.cpp.o
      IlpSolver::initObjective(std::pair<int, std::pair<int, int> > const&) in ilpsolver.cpp.o
      IlpSolver::initMultiSourceSeedingConstraints()      in ilpsolver.cpp.o
      IlpSolver::initLeafConstraints()      in ilpsolver.cpp.o
      IlpSolver::initForcedComigrations()      in ilpsolver.cpp.o
      ...
  "std::__1::__vector_base_common<true>::__throw_length_error() const", referenced from:
      GRBLinExpr::GRBLinExpr(GRBLinExpr const&) in libgurobi_c++.a(LinExpr.o)
      __ZNSt3__16vectorIdNS_9allocatorIdEEE6insertINS_11__wrap_iterIPKdEEEENS_9enable_ifIXaasr21__is_forward_iteratorIT_EE5valuesr16is_constructibleIdNS_15iterator_traitsISA_E9referenceEEE5valueENS5_IPdEEE4typeES8_SA_SA_ in libgurobi_c++.a(LinExpr.o)
      __ZNSt3__16vectorI6GRBVarNS_9allocatorIS1_EEE6insertINS_11__wrap_iterIPKS1_EEEENS_9enable_ifIXaasr21__is_forward_iteratorIT_EE5valuesr16is_constructibleIS1_NS_15iterator_traitsISB_E9referenceEEE5valueENS6_IPS1_EEE4typeES9_SB_SB_ in libgurobi_c++.a(LinExpr.o)
      void std::__1::vector<double, std::__1::allocator<double> >::__push_back_slow_path<double const>(double const&) in libgurobi_c++.a(LinExpr.o)
      void std::__1::vector<GRBVar, std::__1::allocator<GRBVar> >::__push_back_slow_path<GRBVar const>(GRBVar const&) in libgurobi_c++.a(LinExpr.o)
      __ZNSt3__16vectorIdNS_9allocatorIdEEE6assignIPdEENS_9enable_ifIXaasr21__is_forward_iteratorIT_EE5valuesr16is_constructibleIdNS_15iterator_traitsIS7_E9referenceEEE5valueEvE4typeES7_S7_ in libgurobi_c++.a(LinExpr.o)
      __ZNSt3__16vectorI6GRBVarNS_9allocatorIS1_EEE6assignIPS1_EENS_9enable_ifIXaasr21__is_forward_iteratorIT_EE5valuesr16is_constructibleIS1_NS_15iterator_traitsIS8_E9referenceEEE5valueEvE4typeES8_S8_ in libgurobi_c++.a(LinExpr.o)
      ...
  "std::__1::locale::use_facet(std::__1::locale::id&) const", referenced from:
      std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libgurobi_c++.a(LinExpr.o)
      std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libgurobi_c++.a(QuadExpr.o)
  "std::__1::ios_base::getloc() const", referenced from:
      std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libgurobi_c++.a(LinExpr.o)
      std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libgurobi_c++.a(QuadExpr.o)
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__init(char const*, unsigned long)", referenced from:
      GRBLinExpr::remove(int)   in libgurobi_c++.a(LinExpr.o)
      GRBCallback::useSolution()       in libgurobi_c++.a(Callback.o)
      GRBCallback::setcb(GRBCallback*, _GRBmodel*, int) in libgurobi_c++.a(Callback.o)
      GRBCallback::getDoubleInfo(int)    in libgurobi_c++.a(Callback.o)
      GRBCallback::getIntInfo(int)    in libgurobi_c++.a(Callback.o)
      GRBCallback::getStringInfo(int) const in libgurobi_c++.a(Callback.o)
      GRBCallback::getSolution(GRBVar)       in libgurobi_c++.a(Callback.o)
      ...
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__init(unsigned long, char)", referenced from:
      std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> > std::__1::__pad_and_output<char, std::__1::char_traits<char> >(std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> >, char const*, char const*, char const*, std::__1::ios_base&, char) in libgurobi_c++.a(LinExpr.o)
      std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> > std::__1::__pad_and_output<char, std::__1::char_traits<char> >(std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> >, char const*, char const*, char const*, std::__1::ios_base&, char) in libgurobi_c++.a(QuadExpr.o)
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::assign(char const*)", referenced from:
      GRBException::GRBException(int) in libgurobi_c++.a(Exception.o)
      GRBException::GRBException(int) in libgurobi_c++.a(Exception.o)
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      GRBModel::addConstr(GRBTempConstr const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in libgurobi_c++.a(Model.o)
      GRBModel::addGenConstrIndicator(GRBVar, int, GRBTempConstr const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in libgurobi_c++.a(Model.o)
      GRBException::getMessage() const  in libgurobi_c++.a(Exception.o)
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()", referenced from:
      GRBLinExpr::remove(int)   in libgurobi_c++.a(LinExpr.o)
      GRBException::~GRBException() in libgurobi_c++.a(LinExpr.o)
      operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, GRBLinExpr) in libgurobi_c++.a(LinExpr.o)
      std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> > std::__1::__pad_and_output<char, std::__1::char_traits<char> >(std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> >, char const*, char const*, char const*, std::__1::ios_base&, char) in libgurobi_c++.a(LinExpr.o)
      GRBCallback::useSolution()       in libgurobi_c++.a(Callback.o)
      GRBCallback::setcb(GRBCallback*, _GRBmodel*, int) in libgurobi_c++.a(Callback.o)
      GRBException::~GRBException() in libgurobi_c++.a(Callback.o)
      ...
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::operator=(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      GRBEnv::getParamInfo(GRB_StringParam, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in libgurobi_c++.a(Env.o)
      GRBModel::get(GRB_StringAttr, GRBVar const*, int) in libgurobi_c++.a(Model.o)
      GRBModel::get(GRB_StringAttr, GRBConstr const*, int) in libgurobi_c++.a(Model.o)
      GRBModel::get(GRB_StringAttr, GRBQConstr const*, int) in libgurobi_c++.a(Model.o)
      GRBModel::get(GRB_StringAttr, GRBGenConstr const*, int) in libgurobi_c++.a(Model.o)
      GRBException::GRBException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int) in libgurobi_c++.a(Exception.o)
      GRBException::GRBException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int) in libgurobi_c++.a(Exception.o)
      ...
  "std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::sentry(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)", referenced from:
      std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libgurobi_c++.a(LinExpr.o)
      std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libgurobi_c++.a(QuadExpr.o)
  "std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::~sentry()", referenced from:
      std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libgurobi_c++.a(LinExpr.o)
      std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libgurobi_c++.a(QuadExpr.o)
  "std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(double)", referenced from:
      operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, GRBLinExpr) in libgurobi_c++.a(LinExpr.o)
      operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, GRBQuadExpr) in libgurobi_c++.a(QuadExpr.o)
  "std::__1::ctype<char>::id", referenced from:
      std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libgurobi_c++.a(LinExpr.o)
      std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libgurobi_c++.a(QuadExpr.o)
  "std::__1::locale::~locale()", referenced from:
      std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libgurobi_c++.a(LinExpr.o)
      std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libgurobi_c++.a(QuadExpr.o)
  "std::__1::ios_base::__set_badbit_and_consider_rethrow()", referenced from:
      std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libgurobi_c++.a(LinExpr.o)
      std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libgurobi_c++.a(QuadExpr.o)
  "std::__1::ios_base::clear(unsigned int)", referenced from:
      std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libgurobi_c++.a(LinExpr.o)
      std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libgurobi_c++.a(QuadExpr.o)
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [pmh_tr] Error 1
make[1]: *** [CMakeFiles/pmh_tr.dir/all] Error 2`

**Comment by gsatas** [comment]
Hi Joao, 

It looks like you might be running into linking problems with Gurobi. A few things to try: (1) Check that your gurobi is up to date and accessible. (2) Make sure your compiler meets the minimum requirements for gurobi (http://www.gurobi.com/products/supported-platforms)

Best,
Gryte

**Comment by melkebir** [comment]
Hi Joao,

To follow up on Gryte's recommendations, it seems you're trying to compile on macOS. Which version are you using? Also, can you tell me which version of clang and Xcode you're using?

Thanks,
Mohammed

**Comment by jmfa** [comment]
Hi Gryte and Mohammed,
Thanks for the help. 
So, the version of macOS is HighSierra (10.13.4). Xcode version 9.3 and Clang: Apple LLVM version 9.1.0 (clang-902.0.39.1).

Thanks,
J

**Comment by melkebir** [comment]
I'm using the same versions on my mac, and it works for me. How did you compile LEMON? Are you using by any chance a LEMON version that you compiled for AncesTree? If so, please recompile LEMON without editing the CMakeLists.txt file. LEMON needs to be linked against Apple's libc++ instead of libstdc++.

**Comment by jmfa** [comment]
Hmm, that's weird...I compiled Lemon (v1.3) using the instructions on their website (http://lemon.cs.elte.hu/trac/lemon/wiki/InstallLinux)...

**Comment by melkebir** [comment]
Please see https://github.com/raphael-group/machina/releases/download/v1.0/machina-mac.zip for a macOS binary. You will need the latest version of Gurobi (v8.0) though.

**Comment by jmfa** [comment]
Dear Mohammed,
Thank you very much for the binary. 
I've tested all 3 MACHINA modes using the examples provided and everything works perfectly! ;)

**Comment by melkebir** [comment]
Good to hear! Let us know if you run into issues when compiling MACHINA on a linux server (which may be necessary for larger instances).

**Comment by HosseinSnejad** [comment]
Hey,
I'm trying to compile MACHINA on a linux server. I have successfully installed all the dependencies (Gurobi810, Lemon 1.3.1, boost 1_61_0 and CMake 3.17.2). I also installed doxygen. However, when I try to implement command "make" for doxygen, I receive a lot of warnings along with the following error:

src/CMakeFiles/doxycfg.dir/build.make:123: recipe for target 'src/CMakeFiles/doxycfg.dir/__/generated_src/configimpl.cpp.o' failed
make[2]: *** [src/CMakeFiles/doxycfg.dir/__/generated_src/configimpl.cpp.o] Error 1
CMakeFiles/Makefile2:528: recipe for target 'src/CMakeFiles/doxycfg.dir/all' failed
make[1]: *** [src/CMakeFiles/doxycfg.dir/all] Error 2
Makefile:182: recipe for target 'all' failed
make: *** [all] Error 2

I tried to install it several times but always same warnings show up. Regardless of that, I tried to continue. I changed directory to machina/build and successfully implemented "cmake ..". But when I tried "make", I received this message:

-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
Doxygen need to be installed to generate the doxygen documentation
-- Gurobi's home is set to: /opt/gurobi810
-- The retrieved version of Gurobi is: 810
-- The retrieved name of version-specific library is gurobi81
-- Gurobi library /opt/gurobi810/linux64/lib/libgurobi81.so found in /opt/gurobi810/linux64/lib/
-- Configuring done
-- Generating done
-- Build files have been written to: /alina-data0/hossein/machina

After that, I copied "Makefile" from doxygen/build into machina/build and implemented "make" in machina/build directory again. This time, I received the following message:

-- Using Cmake version 3.17.2
-- The javacc executable not found, using existing files
-- Configuring done
-- Generating done
-- Build files have been written to: /alina-data0/hossein/machina/build/doxygen/build
make[1]: CMakeFiles/Makefile2: No such file or directory
make[1]: *** No rule to make target 'CMakeFiles/Makefile2'.  Stop.
Makefile:182: recipe for target 'all' failed
make: *** [all] Error 2

Likewise, I copied "CMakeFiles/Makefile2" directory from /doxygen/build into machina/build and implemented "make" again. I received the following message:

-- Using Cmake version 3.17.2
-- The javacc executable not found, using existing files
-- Configuring done
-- Generating done
-- Build files have been written to: /alina-data0/hossein/machina/build/doxygen/build
make[2]: libmd5/CMakeFiles/md5.dir/build.make: No such file or directory
make[2]: *** No rule to make target 'libmd5/CMakeFiles/md5.dir/build.make'.  Stop.
CMakeFiles/Makefile2:311: recipe for target 'libmd5/CMakeFiles/md5.dir/all' failed
make[1]: *** [libmd5/CMakeFiles/md5.dir/all] Error 2
Makefile:182: recipe for target 'all' failed
make: *** [all] Error 2

In the same way, I copied the relevant directory to machina/build and I got the following message:

-- Using Cmake version 3.17.2
-- The javacc executable not found, using existing files
-- Configuring done
-- Generating done
-- Build files have been written to: /alina-data0/hossein/machina/build/doxygen/build
make[2]: *** No rule to make target '../libmd5/md5.c', needed by 'libmd5/CMakeFiles/md5.dir/md5.c.o'.  Stop.
CMakeFiles/Makefile2:311: recipe for target 'libmd5/CMakeFiles/md5.dir/all' failed
make[1]: *** [libmd5/CMakeFiles/md5.dir/all] Error 2
Makefile:182: recipe for target 'all' failed
make: *** [all] Error 2

I searched in stackoverflow for the solution and it turns out that I am missing "md5.c" file. But I do not have any idea where to find it? It's not in doxygen packet. 
Is it because of those warnings in the process of doxygen installation? If yes, how to resolve it?
Do I need doxygen at all? If no, how to compile MACHINA?
I appreciate your time and help in advance.
