### ISSUE TITLE
Need help for the using of the function cluster

### ISSUE THREAD

**Issue by gorden711411** [raphael-group/machina#4]
Hi, 
I want to use the function "cluster" which is provided by MACHINA. 
But I face some problem when I use it . The following is the error message: 
"Error: Error: m should be nonnegative"
It looks like an input error of my read counts data.
Can you help me to find out the problems of the data.
The attachment is my simulated data.
And I also want to know what should I input of the parameter -C  

Sincerely,
Gorden Pan

[test.zip](https://github.com/raphael-group/machina/files/2052484/test.zip)

**Comment by melkebir** [comment]
Hi Gorden,

For an example input file to cluster, please see:

https://github.com/raphael-group/machina/blob/master/data/sims/m5/mS/reads_seed0.tsv

Here's an example execution:

```
./cluster ../data/sims/m5/mS/reads_seed0.tsv
```

You can ignore parameter -C. (It generates cluster frequencies according to a pre-specified clustering -- we used it to test MACHINA with other clustering algorithms.)

**Comment by gorden711411** [comment]
Thanks a lot.
