### ISSUE TITLE
terminate called after throwing an instance of 'GRBException'

### ISSUE THREAD

**Issue by ghost** [raphael-group/machina#6]
Running your "An example execution of the [...] algorithm:" sections.

Each of the call below are aborted and the results files are empty. Your other example executions from README (./pmh_sankoff, ./generatemutationtrees) run fine. 

Called from the build directory: 

% ./pmh -p LOv -c ../data/mcpherson_2016/coloring.txt ../data/mcpherson_2016/patient1.tree ../data/mcpherson_2016/patient1.labeling -o patient1_constrained/ > patient1_constrained/result.txt
terminate called after throwing an instance of 'GRBException'
Aborted

% ./pmh_tr -p LOv -c ../data/mcpherson_2016/coloring.txt ../data/mcpherson_2016/patient1.tree ../data/mcpherson_2016/patient1.labeling -o patient1_tr/ 2> patient1_tr/result.txt
Aborted

% ./pmh_ti -p breast -c ../data/hoadley_2016/coloring.txt -m 1 -o A7 -F ../data/hoadley_2016/A7/A7_MACHINA_0.95.tsv -barT A7/mutation_trees.txt > A7/result.txt 
Read 2 mutation trees.

terminate called after throwing an instance of 'GRBException'
Aborted

**Comment by melkebir** [comment]
Have you generated a valid Gurobi key using `grbgetkey`?

**Comment by ghost** [comment]
Yes, but now I see that the license is for a single host, which makes it inconvenient to run on a HPC. Never mind, not your problem.

**Comment by melkebir** [comment]
Gurobi has a network license that is free for academia.
