### ISSUE TITLE
executable documentation

### ISSUE THREAD

**Issue by ghost** [raphael-group/machina#7]
Could you please take the time to document each of your executable?  

Like, I don't know to provide you with the "the frequency lower bound and upper bound" and how it should be properly calculated from read counts (could you BTW fix the F.tsv link in your README). I have a feeling cluster could help, but it's undocumented and the --help is not informative about input file format (what is a Read matrix?). You also have other undocumented features. We'd like to cite you, but please help us figure things out. 

 ./cluster --help
Usage:
  ./cluster [--help|-h|-help] [-A] [-C str] [-FWR num] [-a num] [-b num] [-r]
     [-varLB int] R
Where:
  R
     Read matrix
  --help|-h|-help
     Print a short help message
  -A
     Output AncesTree input file
  -C str
     Clustering input filename
  -FWR num
     Family-wise error rate
  -a num
     Confidence interval used for clustering (default: 0.001)
  -b num
     Confidence interval used for pooled frequency matrix (default: 0.01)
  -r
     Relabel mutation clusters
  -varLB int
     Minimum number of variant reads (default: 3)

**Comment by melkebir** [comment]
I updated the documentation. Several steps need to be taken for updating the frequency matrix. First, SNV and CNAs need to be called from the bulk DNA sequencing data. Then, only SNVs that occur in copy-neutral regions need to be retained followed by running a clustering algorithm such as PyClone or SciClone. Alternatively, you could use the cluster executable but I would recommend PyClone or SciClone for real data. Finally, confidence intervals for each cluster in each sample are obtained using beta distribution. Please see the supplement of our paper for more details. Also, the documentation contains a link to a Jupyter notebook for obtaining the frequency matrix for breast cancer patient A7.
